site_name: gXchange

theme:
  name: material
  language: 'pt'
  
nav:
  - Sobre: index.md
  - Léxico: lexico.md
  - Perfil de usuário:
    - Personas: personas.md
  - Diagramas causa-efeito: causa_efeito.md
