site_name: gXchange

theme:
  name: material
  language: "pt"

nav:
  - Sobre: index.md
  - Desenho de Software (Base):
    - 1.1 Módulo Projeto Não Orientado a Abordagens Específicas:
      - 5W2H: 5w2h.md
      - Léxico: lexico.md
      - Diagramas causa-efeito: causa_efeito.md
      - Análise de Riscos: riscos.md
      - Perfil de usuário:
        - Personas: personas.md
  - Versões documentos:
    - Léxico:
      - 1.0: versoes/lexico/1.0.md
      - 1.1: versoes/lexico/1.1.md
      - 1.2: versoes/lexico/1.2.md
    - Análise de Riscos:
      - 1.0: versoes/riscos/1.0.md
