site_name: "gXchange"

theme:
  logo: assets/logos/icon-branco.png
  favicon: assets/logos/icon-branco.png
  name: material
  language: "pt"

extra_css:
  - stylesheets/extra.css

nav:
  - Sobre: index.md
  - Desenho de Software (Base):
    - 1.1 Módulo Projeto Não Orientado a Abordagens Específicas:
      - Rich Picture: rich_picture.md
      - 5W2H: 5w2h.md
      - Léxico: lexico.md
      - Diagramas causa-efeito: causa_efeito.md
      - Análise de Riscos: riscos.md
      - Perfil de usuário:
        - Personas: personas.md
      - Design Sprint:
        - Execução: design_sprint/design_sprint.md
        - Prototipo Média-Fidelidade: design_sprint/prototipo_media.md
        - Prototipo Alta-Fidelidade: design_sprint/prototipo_alta.md
      - Requisitos:
        - Padrões: requisitos/padroes.md
        - Introspecção: requisitos/introspeccao.md
        - Brainstorming: requisitos/brainstorming.md
        - Questionário: requisitos/questionario.md
        - Todos requisitos priorizados: requisitos/requisitos.md
      - Rastro dos participantes: rastro_participantes_1.1.md
      - Apresentação: apresentacao_1.1.md
    - 1.2 Módulo Processos / Metodologias / Abordagens:
      - Metodologias: metodologia.md
      - Modelagem BPMN 2.0: bpmn.md
      - Rastro dos participantes: rastro_participantes_1.2.md
      - Apresentação: apresentacao_1.2.md
  - Desenho de Software (Modelagem):
    - 2.1 Módulo Projeto Orientado a Abordagens Tradicionais:
      - 2.1.1 Notação UML – Diagramas Estáticos:
        - Diagrama de pacotes: diagrama_pacotes.md
        - Diagrama de classes: diagrama_classes.md
        - Diagrama de componentes: diagrama_componentes.md
      - 2.1.2 Notação UML - Diagramas Dinâmicos:
        - Diagramas de Atividade: diagramas_atividades.md
  - Versões documentos:
    - Rich Picture:
      - 1.1: versoes/rich_picture/1.0.md
    - Léxico:
      - 1.0: versoes/lexico/1.0.md
      - 1.1: versoes/lexico/1.1.md
      - 1.2: versoes/lexico/1.2.md
      - 1.3: versoes/lexico/1.3.md
      - 1.4: versoes/lexico/1.4.md
    - Introspecção:
      - 1.0: versoes/introspeccao/1.0.md
    - Padrões requisitos:
      - 1.0: versoes/padroes_requisitos/1.0.md
    - Análise de Riscos:
      - 1.0: versoes/riscos/1.0.md
    - Requisitos:
      - 1.0: versoes/requisitos/1.0.md
    - Diagrama de Classe:
      - 1.0: versoes/diagrama_classe/1.0.md
  - Padrões:
    - Atas: padroes/atas.md
    - Github: padroes/github.md
    - Versões: padroes/versoes.md
    - Documento: padroes/documento.md
  - Atas:
    - Reunião dia 23/02/2021: atas/reuniao_23_02_2021.md
    - Reunião dia 01/03/2021: atas/reuniao_01_03_2021.md
